steps:
  # Build backend
  - id: build-backend
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/todos-backend:latest
      - ./backend

  # Push backend
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/todos-backend:latest

  # Deploy backend
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        'run','deploy','todos-backend',
        '--image','${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/todos-backend:latest',
        '--region','${_REGION}',
        '--platform','managed',
        '--allow-unauthenticated'
      ]

  # Build frontend
  - id: build-frontend
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/todos-frontend:latest
      - ./frontend

  # Push frontend
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/todos-frontend:latest

  # Deploy frontend
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        'run','deploy','todos-frontend',
        '--image','${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/todos-frontend:latest',
        '--region','${_REGION}',
        '--platform','managed',
        '--allow-unauthenticated'
      ]